// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9daFazt8loQBIvUqY1-ERVJ1bT74Oti4',
    appId: '1:615475396118:web:01787081abd39b243d3f37',
    messagingSenderId: '615475396118',
    projectId: 'skilllink-56764',
    authDomain: 'skilllink-56764.firebaseapp.com',
    storageBucket: 'skilllink-56764.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBakT5OnVmEvXbaFkcvwvryHfmxWkRy3ew',
    appId: '1:615475396118:android:2cdf2b53944021873d3f37',
    messagingSenderId: '615475396118',
    projectId: 'skilllink-56764',
    storageBucket: 'skilllink-56764.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqZmtnO4FUqL2SEO9XFNvIhifCVOrkuNU',
    appId: '1:615475396118:ios:dd40da00013136113d3f37',
    messagingSenderId: '615475396118',
    projectId: 'skilllink-56764',
    storageBucket: 'skilllink-56764.firebasestorage.app',
    iosBundleId: 'com.example.skilllink',
  );
}
